### ISSUE TITLE
BOT: Timezone reminder

### ISSUE THREAD

**Issue by criscmaia** [criscmaia/gsdslack#10]
Implement a BOT that will send reminder messages to check if the user has set up the correct time zone on Slack, for example:

"Your time zone is currently set to **(UTC-08:00) Baja California**. Is this correct? 
1. Yes
2. No"

The user has to type either 1/2 or yes/no.

if [YES] - "Great! We can move on to the next step now"

if [NO]:
"Please click on this link to update your time zone:
https://sciencegsd.slack.com/account/settings#timezone "
wait 5 seconds
repeat the original question

"Your time zone is currently set to **(UTC-08:00) Baja California**. Is this correct? 
1. Yes
2. No"

if no response, send the same question next time they are online.

**Comment by btmatthew** [comment]
What do you think of including this as part of the welcome message? 

It would simplify the development.

**Comment by criscmaia** [comment]
Sounds good to me :)

**Comment by btmatthew** [comment]
completed
