### ISSUE TITLE
System crashes when @ a bot

### ISSUE THREAD

**Issue by criscmaia** [criscmaia/gsdslack#12]

**Comment by btmatthew** [comment]
Do you want to keep track of when the user mentioned a bot in a message?

If so we will have to make abot to look like a user in the database. 

Otherwise, we can filter out bot from being mentioned in a message, and that will prevent bot appearing in mentioned table.

**Comment by criscmaia** [comment]
Yes, need to keep track of when a user mentions a bot as well. 
Happy to add as a user if that's the cleanest solution

**Comment by btmatthew** [comment]
Due to relationships in the database that is the sanest solution.

**Comment by btmatthew** [comment]
added the bot to a database, I am waiting for the solution of #22 to continue testing the current solution to #12

**Comment by btmatthew** [comment]
Done, @bot works fine
