### ISSUE TITLE
Adapt and implement DB structure so it stores not only channel messages, but DM as well

### ISSUE THREAD

**Issue by criscmaia** [criscmaia/gsdslack#15]
CHANGES:

Table: slackChannel -> slackChat
slackChannelId -> slackChatId

userTyping
slackChannelId -> slackChatId

Table: channelMessages -> chatMessage
channelMessagesId -> chatMessageId
slackChannelId -> slackChatId

Table: messageReactions -> messageReaction
messageReactionsId -> messageReactionId
channelMessagesId -> chatMessageId

Table: messageMentions -> messageMention
messageMentionsId -> messageMentionId
channelMessagesId -> chatMessageId

**Comment by criscmaia** [comment]
Done!

**Comment by btmatthew** [comment]
Will have to update the code next.

**Comment by btmatthew** [comment]
Completed and working
