### ISSUE TITLE
Implement profile survey through direct message

### ISSUE THREAD

**Issue by criscmaia** [criscmaia/gsdslack#16]
Changing the implementation method described on #9.

Questions and answer options for every survey are stored at surveyQuestions and surveyOption.

On the agreed time, the system will print the first question, followed by the options, for example:
Are you more impressed by:
1. Emotions
2. Principles

Then the user will type either 1 or 2 and send.

If the question displayed is not the 1st one, there will be always an extra option to go back to the previous question.

If the user leaves Slack without completing the survey, he/she will get a reminder when it comes back online.
There will be only 2 reminders per question. If the user still doesn't reply after the 2nd reminder, the survey will be closed.

**Reminder messages:**
"this is the 1st reminder that you haven't replied to the previous question", then repeat the question.
"this is the 2nd and **last** reminder that you haven't replied to the previous question. If you don't reply before leaving Slack, this survey will automatically close.", then repeat the question.

**Comment by criscmaia** [comment]
![image](https://user-images.githubusercontent.com/9072422/28779981-093556dc-75fd-11e7-94e5-60939ea52ef3.png)

**Comment by criscmaia** [comment]
MBTI code: https://raw.githubusercontent.com/criscmaia/gsdforms/master/mbti.php?token=AIpvJg7zR-haIv2Tn6tUGKP8AePvd3FEks5ZiG51wA%3D%3D

**Comment by criscmaia** [comment]
PAEI code: https://raw.githubusercontent.com/criscmaia/gsdforms/master/paei.php?token=AIpvJmrgOO1CZhA7zGLT9Lcxm1cGAy1Aks5ZiG6ywA%3D%3D

**Comment by btmatthew** [comment]
Please update column survyeVAK to surveyVAK in activityTracker. @criscmaia

**Comment by criscmaia** [comment]
Done!

**Comment by criscmaia** [comment]
The tracking of which was the last question answered by the student **and** the number of reminders given per question will be stored on the table activityTracker.

**Comment by btmatthew** [comment]
Please tell me how do you want to display the final score of the survey?

**Comment by criscmaia** [comment]
MBTI:
![image](https://user-images.githubusercontent.com/9072422/29118031-598b691c-7cf8-11e7-8ebf-6acd41efda7d.png)
Link: https://gsd.mdx.ac.uk/gsdforms/mbti.pdf


PAEI:
![image](https://user-images.githubusercontent.com/9072422/29118087-858aedee-7cf8-11e7-9c04-aed59f113603.png)


Screenshots from the php website.

**Comment by btmatthew** [comment]
For PAEI slack will have trouble displaying some much data. We should consider some other options.
For MBTI is that everything that should be displayed?

**Comment by btmatthew** [comment]
Implemented the result messages to both PAEI, and MBTI. Could you please test it and confirm if you like it?

**Comment by criscmaia** [comment]
**MBTI** yes, grouped in pairs and the highest score for each pair joins with the next to form the result.
If the pair has the same result, show both results. Example:
E: 5	S: 13	T: 16	J: 14
I: 5	N:  7		F:  4		P:  6
You are an: **ESTJ** and **ISTJ**
Click here to access the PDF will full explanation (_link_)

**PAEI** can we have each paragraph in a separate message? So it will be 4 messages in total to show the results.

**Comment by btmatthew** [comment]
Implemented, let me know when you want to test it.

**Comment by criscmaia** [comment]
PAEI display looking great. Only missing a big bold **## RESULTS:** as an individual message just before showing the 4 messages with the actual result

**Comment by criscmaia** [comment]
MBTI looks great as well! One minor mistake, extra **)** in the end:
![image](https://user-images.githubusercontent.com/9072422/29211000-4e043ffa-7e8e-11e7-8646-8aff450ac424.png)

**Comment by btmatthew** [comment]
Can't do bold, tried and doesn't work

**Comment by criscmaia** [comment]
The results for MBTI is bold :|

**Comment by btmatthew** [comment]
The bold part of the text is a title of the message.
In MBTI the title is set as word "Result"
In the case of PAEI, the title is the score that user received.

**Comment by criscmaia** [comment]
Can we have a message on its own, before the actual results, only with **Results:**  ?

**Comment by criscmaia** [comment]
Done!
