### ISSUE TITLE
Keep track of steps completed by the user

### ISSUE THREAD

**Issue by criscmaia** [criscmaia/gsdslack#19]
If he has received/read the welcome message
If the has updated his timezone
If they have answered the dummy survey
If they have finished the last survey. Or what the last question answered was.

**Comment by criscmaia** [comment]
The ideal scenario is to link it with SOBs system but for now, we'll have a separate table to keep track of it.

**Comment by criscmaia** [comment]
![image](https://user-images.githubusercontent.com/9072422/28784349-16f3b666-760b-11e7-88b7-f1479ee739e6.png)

**Comment by btmatthew** [comment]
@criscmaia 
Can we make userId of activityTracker a foreign key slackUserId of slackUser table?
Otherwise, I will have to query a database to find userId from user table based on slackUserId.

**Comment by criscmaia** [comment]
![image](https://user-images.githubusercontent.com/9072422/28820944-6f534f9c-76ab-11e7-8ac8-9b4f0ef2657f.png)

Temporary solution before SOBs is implemented.
Ideally we want to connect to the user table as we may have tasks for users who are not part of Slack

**Comment by btmatthew** [comment]
completed
