### ISSUE TITLE
Implement dummy survey

### ISSUE THREAD

**Issue by criscmaia** [criscmaia/gsdslack#20]
"You will be asked some multiple choice questions during the project. To answer it, you just need to type the number of the option you want to choose and send the message. If you type an invalid option, the same question will repeat.
1. I like how it works, let's start.
2. I'm not sure if I like it, but let's try.
3. I don't think it's a good way to do it.

After the first question, you will be given an extra option to go back to the previous question. 
1. That's a good idea!
2. I don't think it's relevant.
3. Go back to the previous question.

After answering the last question, you will receive a confirmation message and, if relevant, the results of your survey. If you have any question don't hesitate to contact the admins.
1. All clear.
2. I have some questions, I'll be contacting the admin.
3. Go back to the previous question.

Congratulations! You've now concluded the testing survey."

**Comment by criscmaia** [comment]
After 1st test:
Dots missing after the number.
No go back options

**Comment by btmatthew** [comment]
After 1st test (for all surveys, not only dummy): **Done**
Dots missing after the number. **Done**
No go back options **Done**
Give the questions numbers **Done**
Nothing after last question is answered **WIP**

**Comment by btmatthew** [comment]
Nothing after last question is answered **Done**
