### ISSUE TITLE
Implement VARK

### ISSUE THREAD

**Issue by criscmaia** [criscmaia/gsdslack#26]
**DB tables:**
surveyVark - surveyVarkChosenOptions
surveyQuestion - surveyOption

1) Question
A) Option 1
B) Option 2
C) Option 3
D) Option 4
E) none of the above
User input: (any letter between A and E

[The-VARK-Questionnaire_201701007.pdf](https://github.com/criscmaia/gsdslack/files/1415749/The-VARK-Questionnaire_201701007.pdf)

**Comment by btmatthew** [comment]
@criscmaia 
> A) Option 1
B) Option 2
C) Option 3
D) Option 4

I think it would be easier for the user to enter numbers rather than letters. What do you think?
I will also have to mess around with code to set answers with letters rather than numbers.

**Comment by criscmaia** [comment]
The questions are numbered, so we don't want to confuse them having the options being numbered as well, better to have letters really.

**Comment by btmatthew** [comment]
> User input: (any letter between A and D or 0 to none.
Value of 0 is used for purpose of returning to the previous question. Please provide an alternative solution.

**Comment by criscmaia** [comment]
Updated. E for "None of the above"

**Comment by btmatthew** [comment]
Can you double check haskmap of questions to vark values please?
`val map: HashMap<Int, HashMap<Char,Char>> = hashMapOf(
            1 to hashMapOf('a' to 'k', 'b' to 'a','c' to 'r','d' to 'v'),
            2 to hashMapOf('a' to 'v', 'b' to 'a','c' to 'r','d' to 'k'),
            3 to hashMapOf('a' to 'k', 'b' to 'v','c' to 'r','d' to 'a'),
            4 to hashMapOf('a' to 'k', 'b' to 'a','c' to 'v','d' to 'r'),
            5 to hashMapOf('a' to 'a', 'b' to 'v','c' to 'k','d' to 'r'),
            6 to hashMapOf('a' to 'k', 'b' to 'r','c' to 'v','d' to 'a'),
            7 to hashMapOf('a' to 'k', 'b' to 'a','c' to 'v','d' to 'r'),
            8 to hashMapOf('a' to 'r', 'b' to 'k','c' to 'a','d' to 'v'),
            9 to hashMapOf('a' to 'r', 'b' to 'a','c' to 'k','d' to 'v'),
            10 to hashMapOf('a' to 'k', 'b' to 'v','c' to 'r','d' to 'a'),
            11 to hashMapOf('a' to 'v', 'b' to 'r','c' to 'a','d' to 'k'),
            12 to hashMapOf('a' to 'a', 'b' to 'r','c' to 'v','d' to 'k'),
            13 to hashMapOf('a' to 'k', 'b' to 'a','c' to 'r','d' to 'v'),
            14 to hashMapOf('a' to 'k', 'b' to 'r','c' to 'a','d' to 'v'),
            15 to hashMapOf('a' to 'k', 'b' to 'a','c' to 'r','d' to 'v'),
            16 to hashMapOf('a' to 'v', 'b' to 'a','c' to 'r','d' to 'k'))
`

**Comment by criscmaia** [comment]
Checked!

**Comment by btmatthew** [comment]
@criscmaia When should submission time for vark be placed?
Every time user answered the question?
When user completed answering all the questions?

**Comment by criscmaia** [comment]
Every question, so we can track where it stopped and reminders

**Comment by criscmaia** [comment]
Implemented. To be tested.
