### ISSUE TITLE
VARK: ignore wrong characters if there is a valid one

### ISSUE THREAD

**Issue by criscmaia** [criscmaia/gsdslack#30]
![image](https://user-images.githubusercontent.com/9072422/32418047-926381e6-c25a-11e7-83bb-a0d4cbfef589.png)

**Comment by criscmaia** [comment]
Similar issue, it lets you submit a valid option more than once

![image](https://user-images.githubusercontent.com/9072422/32418072-cd1a63fe-c25a-11e7-99bc-a6c3fa0b0903.png)

**Comment by btmatthew** [comment]
In case of D1 it will filter out anything that is not value between A and E or 0.

I am using regex to filter out all the values. 

In case of AAAA it will only look for value of A in the answer once, so you can enter 100 times A and it will still count as A once :)

**Comment by criscmaia** [comment]
Excellent. Let's just have it output as incorrect answer and ask the user
to try again instead of filtering the correct one.

**Comment by btmatthew** [comment]
nope

**Comment by criscmaia** [comment]
?

**Comment by btmatthew** [comment]
updated

**Comment by btmatthew** [comment]
updated a response

**Comment by btmatthew** [comment]
Update, the bot will shout at you whenever you type an incorrect value.

**Comment by criscmaia** [comment]
Error message is:
Incorrect value please select ABCD values, or type 0 to return to previous question.

Should mention E option as well, but not sure how. Will get George to come up with the best sentence.

Still doing the main test

**Comment by criscmaia** [comment]
Correct:
A0 or 0A doesn't work. Good!

Incorrect:
AAA still works. It shouldn't. Can't assume that they meant to type only one A.
ABE works. It shouldn't. You either select between A to D or E for none.

**Comment by btmatthew** [comment]
(aa+|bb+|cc+|dd+|ee+|a+0|b+0|c+0|d+0|a+e|b+e|c+e|d+e|e+a|e+b|e+c|e+d)
Hopefully this will make the bot even more anoying....

**Comment by btmatthew** [comment]
(aa+|bb+|cc+|dd+|ee+|a+0|b+0|c+0|d+0|a+e|b+e|c+e|d+e|e+a|e+b|e+c|e+d)|[^a-e -]|(0-9)
This will make it even more anoying

**Comment by btmatthew** [comment]
Please test and let me know if it is all fine.

**Comment by criscmaia** [comment]
**Testing everything**
_Timezone set up_ - good
_survey dummy_ - good
_MBTI_ - good
_PAEI_ - almost good: the RESULTS brackets are messed up: P(15), A(16, E(15), I(9))
_VARK_ - wrong:
**1)** my VARK table is not clear 
**2)** inputs issues:
ABA works (bad)
BAB works (bad)
0A0 doesn't work (good)
BAA doesn't work (good)
ACC doesn't work (good)
0 deletes row from surveyVarkChosenOptions (great)
**3)** add results description (Cristiano to provide details)

**Comment by btmatthew** [comment]
>  my VARK table is not clear (this means that if a student does up to question 10, stops, start again (for whatever reason we allow) and do up to 5, it will have the last 5 from the 1st attempt meaning two attempts together)

No clue what you are talking about....

> 2) inputs issues:
ABA works (bad)
BAB works (bad)

Done please check

**Comment by criscmaia** [comment]
All working! \o/
