### ISSUE TITLE
VARK: responses are not being saved on the DB

### ISSUE THREAD

**Issue by criscmaia** [criscmaia/gsdslack#31]
It works:
- Activity tracker is updated when the survey finishes

It doesn't work:
- Save to _surveyVarkChosenOptions_ after every answer. If the user goes back a question, this table can be ignored.
- Update the _surveyVark_ table with the ID from last inserted according to point above. If the user goes back, it should set **Qxx** to **NULL**.
- The survey doesn't start again when _activityTracker_ table, column _surveyVark_, is set to **null**.

**Comment by btmatthew** [comment]
The row for surveyPAEI, surveyVARK, or survayMBTI are created when the system sent the instructions on how to answer the surveys.

At the time when you completed PAEI there was no VARK so the system never created surveyVARK row for you.

I have removed your previous answers for PAEI and MBTI, please complete them and VARK row should be created automatically.

**Comment by btmatthew** [comment]
Update the system should now work, all of the surveys working after doing a quick smoke test.

**Comment by criscmaia** [comment]
Working brilliantly! Great job
