### ISSUE TITLE
MBTI and PAEI: not showing question options

### ISSUE THREAD

**Issue by criscmaia** [criscmaia/gsdslack#32]
![image](https://user-images.githubusercontent.com/9072422/32486830-bd027632-c39f-11e7-9c1a-d9f6fd09b262.png)

**Comment by criscmaia** [comment]
That was just for the 1st question. The following ups works fine

**Comment by criscmaia** [comment]
![image](https://user-images.githubusercontent.com/9072422/32487016-4d4cec36-c3a0-11e7-927c-0e06da9dbf77.png)

Same issue for PAEI

**Comment by criscmaia** [comment]
It works fine for VARK

![image](https://user-images.githubusercontent.com/9072422/32487078-837a23dc-c3a0-11e7-88fc-ad742d281806.png)

**Comment by btmatthew** [comment]
Fixed please test it
