### ISSUE TITLE
VARK: add results description

### ISSUE THREAD

**Issue by criscmaia** [criscmaia/gsdslack#33]

**Comment by criscmaia** [comment]
[ One paragraph per slack message ]

**Visual:** _(score number here)_
Someone with a Visual learning style has a preference for seen or observed things, including pictures, diagrams, demonstrations, displays, handouts, films, flip-chart, etc. These people will use phrases such as ‘show me’, ‘let’s have a look at that’ and will be best able to perform a new task after reading the instructions or watching someone else do it first. These are the people who will work from lists and written directions and instructions.

**Aural:** _(score number here)_
Someone with an Aural learning style has a preference for the transfer of information through listening: to the spoken word, of self or others, of sounds and noises. These people will use phrases such as ‘tell me’, ‘let’s talk it over’ and will be best able to perform a new task after listening to instructions from an expert. These are the people who are happy being given spoken instructions over the telephone, and can remember all the words to songs that they hear!

**Read/write:** _(score number here)_
This preference is for information displayed as words. Not surprisingly, many teachers and students have a strong preference for this mode. Being able to write well and read widely are attributes sought by employers of graduates. This preference emphasizes text-based input and output – reading and writing in all its forms but especially manuals, reports, essays and assignments. People who prefer this modality are often addicted to PowerPoint, the Internet, lists, diaries, dictionaries, thesauri, quotations and words, words, words… Note that most PowerPoint presentations and the Internet, GOOGLE and Wikipedia are essentially suited to those with this preference as there is seldom an auditory channel or a presentation that uses Visual symbols.

**Kinaesthetic**: _(score number here)_
Someone with a Kinaesthetic learning style has a preference for physical experience - touching, feeling, holding, doing, practical hands-on experiences. These people will use phrases such as ‘let me try’, ‘how do you feel?’ and will be best able to perform a new task by going ahead and trying it out, learning as they go. These are the people who like to experiment, hands-on, and never look at the instructions first!

People commonly have a main preferred learning style, but this will be part of a blend of all four. Some people have a very strong preference; other people have a more even mixture of two or less commonly, three styles.

When you know your preferred learning style(s) you understand the type of learning that best suits you. This enables you to choose the types of learning that work best for you. There is no right or wrong learning style. The point is that there are types of learning that are right for your own preferred learning style.

**Comment by criscmaia** [comment]
Reminder

**Comment by btmatthew** [comment]
Done, please test it

**Comment by criscmaia** [comment]
Result not being calculated.
Result description not showing.

![image](https://user-images.githubusercontent.com/9072422/34986371-408e77a8-faaf-11e7-8dd9-3a8a890a46ab.png)

**Comment by criscmaia** [comment]
Test 1:
1- activityTracker table, set 0 to surveyPAEI and surveyVARK
2-refresh Slack
// no new message showing.
3-press 1 and send (as if it was answering a question)
// nothing
4-press 1 and send (as if it was answering a question)
// nothing

The application may not be running.

**Comment by criscmaia** [comment]
The bot application was down. Testing II:

2-refresh Slack
// no new message showing.
3-press 1 and send (as if it was answering a question)
// shows question 2. It means that I've just answered question 1 even if it wasn't showing. Bad.
4-repeat until it shows q8
//activityTracker.lastAnsweredQuestion shows as 7. Good.
5-Repeat until end of PAEI.
//Results are displayed, but all 0. Bad.
//VARK introduction. Good.
6-Press 1
//incorrect message value. Good.
7-Press A until q5
//valid answers, shows next question.
//activityTracker.lastAnsweredQuestion shows as 4. Good.
8-Repeat until the end
//short results are shown. Bad.
//They are all 0. Bad.
//Shows message that I've completed all the activities. Good.

**Comment by criscmaia** [comment]
Test III - starting with blank activityTracker:

1-Load Slack
// no timezone message. Bad
// activityTracker.welcomeDM still set as NULL
2-Type 1
// start dummy survey. Good
3-Repeat until MBTI start
//shows introduction. Good
4-Repeats until end of MBTI survey
// shows results. Good
// shows intro to PAEI. Good
5-Type 1 until end of PAEI
// show short and detailed results. Good
// show VARK intro
6-Type ABC until end of VARK
// shows the detailed result. Good
// shows "completed activity". Good
