### ISSUE TITLE
Thread header-message deletion time is being updated when a sub-message is deleted as well

### ISSUE THREAD

**Issue by criscmaia** [criscmaia/gsdslack#7]

**Comment by btmatthew** [comment]
"UPDATE channelMessages AS t1 INNER JOIN (" +
                    "SELECT userTimezoneOffset FROM channelMessages WHERE slackMessageId = ? LIMIT 1)" +
                    " AS t2 SET t1.deletedLocaltime = DATE_ADD(UTC_TIMESTAMP(), INTERVAL (3600 * t2.userTimezoneOffset) SECOND)" +
                    " WHERE slackMessageId = ?;"

check your sql query it is the only thing that could be wrong.

**Comment by btmatthew** [comment]
nvm Slack was being funny again and kept on sending multiple delete requests. Fixed that can you test that?

**Comment by criscmaia** [comment]
Fixed
